# Generated by Django 3.1.4 on 2021-09-06 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210819_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 6, 13, 32, 10, 787887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 9, 6, 13, 32, 10, 787786, tzinfo=utc)),
        ),
    ]
